# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_auto_20160515_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcommande',
            name='execution_vue',
            field=models.BooleanField(default=False, verbose_name='Ex\xe9cution vue'),
        ),
    ]
